[build]
  publish = "."

[[redirects]]
  from = "/proud-to-pay"
  to = "/proud-to-pay.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/support"
  to = "/support.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/brand-films-charlotte"
  to = "/brand-films-charlotte.html"
  status = 200

[[redirects]]
  from = "/brand-photography-charlotte"
  to = "/brand-photography-charlotte.html"
  status = 200

[[redirects]]
  from = "/ongoing-content-charlotte"
  to = "/ongoing-content-charlotte.html"
  status = 200
